### ISSUE TITLE
Error in nonce

### ISSUE THREAD

**Issue by edgar017** [jorijnsmit/poloniex_wrapper#1]
Array
(
    [error] => Nonce must be greater than 1485429661919364. You provided 1485143766413221.
)

**Comment by jorijnsmit** [comment]
Can you provide a more complete description of what it is you were doing that created this error?

**Comment by jorijnsmit** [comment]
This can happen when you are using the same API key for different applications or executing API calls in parallel. Make sure for every call that the nonce is greater than the one before.

From the [official documentation](https://poloniex.com/support/api/):
> Additionally, all queries must include a "nonce" POST parameter. The nonce parameter is an integer which must always be greater than the previous nonce used.
