### ISSUE TITLE
Public API not working 

### ISSUE THREAD

**Issue by Aabir1** [jorijnsmit/poloniex_wrapper#2]
I am trying with different parameters but it always giving me 403 .
I am working on
Localhost
UBUNTU
Firefox

file_get_contents(https://poloniex.com/public?0=returnCurrencies): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden

**Comment by jorijnsmit** [comment]
Try calling `file_get_contents(https://poloniex.com/public?command=returnCurrencies)` instead. Please see also Poloniex' documentation at [https://poloniex.com/support/api/](url).
