### ISSUE TITLE
buy

### ISSUE THREAD

**Issue by AMONRA75** [jorijnsmit/poloniex_wrapper#3]
hi,
how can I open an order with the buy function?
can you give me an example?
tnx a lot!

**Comment by jorijnsmit** [comment]
The [buy function](https://github.com/jorijnsmit/poloniex_wrapper/blob/67fe68ecdbbc611dcbe3e2fbd1394dfc32b40254/Poloniex.php#L298) does exactly what you need.

I am not here to explain basic function calling in php to you though... Try some tutorials first or take some classes on [Udemy](https://www.udemy.com/php-for-complete-beginners-includes-msql-object-oriented/), [coursera](https://www.coursera.org/courses?languages=en&query=php) or [Codecademy](https://www.codecademy.com/en/tracks/php).
