### ISSUE TITLE
Invalid API key

### ISSUE THREAD

**Issue by simonreger** [jorijnsmit/poloniex_wrapper#4]
Hello, i have an valide API Key and secret. But when i use the Function returnCompleteBalances() i get this error message:
Array ( [error] => Invalid API key/secret pair. ) 

What did i wrong?

**Comment by simonreger** [comment]
functions like returnTicker() are working. But the private Methods produce the Error. 

This is my Backend for Poloniex API:
![grafik](https://user-images.githubusercontent.com/32191953/169773268-6c3f53b9-2c3f-47f0-9fd7-962cbd91eaf8.png)

**Comment by jorijnsmit** [comment]
did you whitelist the right ip?

am afraid this is just a mismatch between your api keys config and the actual api access settings.

**Comment by jorijnsmit** [comment]
good to hear!
